# mod_mutations.R — somatic mutation landscape

mod_mutations_ui <- function(id) {
  ns <- NS(id)
  tagList(
    br(),
    div(class = "alert alert-info",
      h5("About Somatic Mutations"),
      p("RNA-seq tells us ", strong("what is being expressed"), " — but not ", strong("why"),
        ". Somatic mutations are the DNA-level drivers: point mutations, small insertions/deletions
        (indels), and splice-site disruptions that arise in tumor cells and are absent in normal tissue.
        TCGA provides ", strong("Masked Somatic Mutation (MAF)"), " files with all validated somatic
        variants per patient, generated by the GDC somatic variant calling pipeline."),
      p("We analyze:", tags$ul(style="margin-bottom:0",
        tags$li(strong("Mutation landscape:"),
          " Which genes are mutated, how often, and what type of mutation."),
        tags$li(strong("Tumor Mutational Burden (TMB):"),
          " Total number of somatic mutations per patient — a biomarker for immunotherapy response."),
        tags$li(strong("OncoPrint:"),
          " Patient-by-gene matrix showing who has mutations in which driver genes simultaneously."),
        tags$li(strong("Survival impact:"),
          " Does mutation of a specific gene (e.g. TP53) affect overall survival?")
      ))
    ),
    div(class = "alert alert-success",
      h5("Key findings — TCGA-BRCA mutation landscape (n = 1,020 patients, 85,864 mutations)"),
      tags$ul(
        tags$li(strong("PIK3CA (34.5%) and TP53 (34.3%) are co-dominant drivers"),
          " — nearly identical frequency but in almost completely different patient populations.
          PIK3CA mutations cluster in Luminal A/B (HR+ tumors with stable genomes);
          TP53 mutations dominate in Triple-Negative and HER2-enriched subtypes (high chromosomal instability)."),
        tags$li(strong("CDH1 mutated in 12.7% of patients"),
          " — CDH1 encodes E-cadherin, the key epithelial cell-adhesion protein.
          Its loss is the defining event of ", em("invasive lobular carcinoma"),
          " (the second most common BRCA histology). Almost all CDH1-mutant patients have Luminal A tumors."),
        tags$li(strong("GATA3 (12.5%) and MAP3K1 (8.8%)"),
          " are Luminal-specific transcription factor/signaling mutations
          associated with better prognosis — they refine hormone receptor biology rather than driving aggressive disease."),
        tags$li(strong("TTN (18.9%) is a passenger mutation"),
          " — Titin is the largest human protein and largest gene (~280 kb),
          so it accumulates random mutations simply by being a large target.
          High TTN mutation rate is a TMB proxy, not a functional driver."),
        tags$li(strong("TMB median = 39 mutations/patient (≈ 1.3 mut/Mb)"),
          " — far below lung cancer (~10 mut/Mb) or melanoma (~20 mut/Mb).
          One hypermutated outlier reaches 5,360 mutations (likely POLE/MMR-deficient).
          Low TMB = few neoantigens = poor immunotherapy response in unselected BRCA patients.")
      )
    ),
    tabsetPanel(
      # --- Mutation Landscape ---
      tabPanel("Mutation Landscape",
        br(),
        div(style = "text-align:center; background:#f8f9fa; padding:10px; border-radius:6px;",
          imageOutput(ns("freq_img"), height = "560px", width = "100%")
        ),
        br(),
        div(class = "alert alert-secondary",
          h6("How to read this chart"),
          tags$ul(style = "margin-bottom:0",
            tags$li(strong("Y-axis:"), " Genes ranked by mutation frequency (most mutated at top)."),
            tags$li(strong("X-axis:"), " Number of mutations (a single patient can contribute
              multiple mutations in the same gene)."),
            tags$li(strong("Bar colors = mutation type:"),
              " Blue = Missense (amino acid change, may or may not affect protein function);
              Red = Nonsense (premature stop codon, truncates protein — almost always damaging);
              Orange = Frameshift deletion; Purple = Frameshift insertion."),
            tags$li(strong("Percentage label:"),
              " Fraction of patients with ≥1 somatic mutation in that gene.
              TP53 ~35% and PIK3CA ~35% are the dominant drivers in BRCA.")
          )
        )
      ),
      # --- OncoPrint ---
      tabPanel("OncoPrint",
        br(),
        div(class = "alert alert-secondary",
          h6("What is an OncoPrint?"),
          p("Each column = one patient. Each row = one gene. A colored block means that patient
            has a somatic mutation in that gene. The bar chart on the right shows total mutation
            frequency. The bar chart on top shows total mutations per patient (TMB proxy).",
            style = "margin-bottom:4px;"),
          p("The clinical annotation bar at the top shows tumor stage for each patient,
            letting you see whether certain mutation patterns are enriched in early vs. late stage.",
            style = "margin-bottom:0;")
        ),
        div(style = "text-align:center; background:#f8f9fa; padding:10px; border-radius:6px;",
          imageOutput(ns("onco_img"), height = "560px", width = "100%")
        )
      ),
      # --- Co-occurrence ---
      tabPanel("Co-occurrence / Exclusivity",
        br(),
        div(class = "alert alert-secondary",
          h6("Co-occurrence and mutual exclusivity"),
          tags$ul(style = "margin-bottom:0",
            tags$li(strong("Co-occurrence (green):"),
          " Two genes are mutated together more often than expected by chance — may indicate cooperating drivers.
          Example: HMCN1 + TTN co-occur (OR = 4.6, p = 2.3×10⁻⁸), both likely passengers accumulating in
          genetically unstable tumors rather than functional cooperators."),
        tags$li(strong("Mutual exclusivity (red):"),
          " Two genes are almost never mutated in the same patient. Top hits in BRCA:"),
        tags$ul(
          tags$li(strong("PIK3CA vs TP53:"), " only 82 co-occurrences out of 538 total (p = 8.7×10⁻⁸).
            PIK3CA mutations drive Luminal A/B; TP53 mutations drive TNBC/HER2+. Different diseases."),
          tags$li(strong("GATA3 vs TP53:"), " only 11 co-occurrences out of 456 (p = 1.5×10⁻¹²).
            GATA3 is a luminal transcription factor — incompatible with the aggressive TP53-mutant phenotype."),
          tags$li(strong("CDH1 vs TP53:"), " only 9 co-occurrences out of 462 (p = 1.5×10⁻¹⁴).
            The strongest exclusivity signal: lobular BRCA (CDH1 loss) and basal BRCA (TP53 loss)
            are essentially separate diseases at the molecular level.")
        ),
        tags$li(strong("* / ** / ***:"),
          " Statistical significance (Fisher's exact test, Benjamini-Hochberg correction).")
          )
        ),
        div(style = "text-align:center; background:#f8f9fa; padding:10px; border-radius:6px;",
          imageOutput(ns("cooccur_img"), height = "560px", width = "100%")
        )
      ),
      # --- TMB ---
      tabPanel("Tumor Mutational Burden",
        br(),
        div(style = "text-align:center; background:#f8f9fa; padding:10px; border-radius:6px;",
          imageOutput(ns("tmb_img"), height = "460px", width = "100%")
        ),
        br(),
        div(class = "alert alert-secondary",
          h6("What is TMB and why does it matter?"),
          tags$ul(style = "margin-bottom:0",
            tags$li(strong("TMB (Tumor Mutational Burden)"),
              " = total number of somatic non-synonymous mutations per patient.
              Higher TMB → more neoantigens → more likely the immune system can recognize
              and attack the tumor → better response to immune checkpoint inhibitors (ICI)."),
            tags$li(strong("In BRCA, TMB median = 39 raw mutations per patient (range: 1–5,360)"),
              " — approximately 1.3 mut/Mb on a 30 Mb exome. Far below melanoma (~20) or NSCLC (~10).
              Low TMB = few neoantigens = poor immunotherapy response in unselected BRCA patients."),
            tags$li(strong("The outlier at 5,360 mutations"),
              " is a hypermutated (likely POLE/MMR-deficient) tumor.
              These ultra-high-TMB cases (~1% of BRCA) qualify for pembrolizumab
              under the FDA's tumor-agnostic MSI-High approval."),
            tags$li(strong("TMB vs. Stage:"),
              " Stage IV tumors may accumulate more mutations through continued clonal evolution,
              but the relationship is noisier in BRCA than in colorectal or lung cancer.")
          )
        )
      ),
      # --- Survival by mutation ---
      tabPanel("Survival by Mutation",
        br(),
        div(class = "alert alert-info",
          h6("Does a specific mutation affect survival?"),
          p("Select a gene from the dropdown. Patients are split into ", strong("Mutated"),
            " vs ", strong("Wild-type"), " groups based on whether they carry ≥1 somatic
            mutation in that gene. A log-rank test and Kaplan-Meier curve compare survival.
            Note: mutation status may correlate with subtype — always consider confounders.")
        ),
        fluidRow(
          column(4,
            wellPanel(
              selectInput(ns("gene_mut"), "Select gene:",
                          choices  = NULL,
                          selected = NULL),
              hr(),
              uiOutput(ns("mut_stats"))
            )
          ),
          column(8,
            plotOutput(ns("km_mut"), height = "440px")
          )
        ),
        div(class = "alert alert-secondary",
          h6("Interpretation guide"),
          tags$ul(style = "margin-bottom:0",
            tags$li(strong("TP53 mutant vs WT:"),
              " TP53 mutations are enriched in aggressive TNBC. Expect significantly worse
              survival in mutant patients — but remember this confounds with subtype."),
            tags$li(strong("PIK3CA mutant vs WT:"),
              " PIK3CA mutations occur mainly in Luminal A/B (favorable prognosis).
              Expect better survival in mutants — again confounded by subtype."),
            tags$li(strong("CDH1:"),
              " Marks lobular BRCA, which has distinct biology and intermediate prognosis."),
            tags$li("A significant p-value here does NOT prove the mutation causes the
              survival difference — it may be a proxy for subtype.")
          )
        )
      )
    )
  )
}

mod_mutations_server <- function(id, mut_res, figures_dir) {
  moduleServer(id, function(input, output, session) {

    # Populate gene dropdown
    observe({
      req(mut_res)
      genes <- mut_res$driver_genes
      updateSelectInput(session, "gene_mut",
                        choices  = genes,
                        selected = genes[1])
    })

    # Static images
    output$freq_img <- renderImage({
      list(src = file.path(figures_dir, "mutation_freq.png"),
           contentType = "image/png", width = "100%", alt = "Mutation frequency")
    }, deleteFile = FALSE)

    output$onco_img <- renderImage({
      list(src = file.path(figures_dir, "oncoprint.png"),
           contentType = "image/png", width = "100%", alt = "OncoPrint")
    }, deleteFile = FALSE)

    output$cooccur_img <- renderImage({
      list(src = file.path(figures_dir, "mutation_cooccurrence.png"),
           contentType = "image/png", width = "100%", alt = "Co-occurrence")
    }, deleteFile = FALSE)

    output$tmb_img <- renderImage({
      list(src = file.path(figures_dir, "mutation_tmb.png"),
           contentType = "image/png", width = "100%", alt = "TMB")
    }, deleteFile = FALSE)

    # Stats box
    output$mut_stats <- renderUI({
      req(input$gene_mut, mut_res)
      gene <- input$gene_mut
      df   <- mut_res$surv_mut
      if (!gene %in% colnames(df)) return(p("No data for this gene."))
      n_mut <- sum(df[[gene]] == 1, na.rm = TRUE)
      n_wt  <- sum(df[[gene]] == 0, na.rm = TRUE)
      pct   <- round(100 * n_mut / (n_mut + n_wt), 1)
      gf    <- mut_res$gene_freq[mut_res$gene_freq$Hugo_Symbol == gene, ]
      tagList(
        tags$table(class = "table table-sm",
          tags$tr(tags$td("Gene"),      tags$td(strong(gene))),
          tags$tr(tags$td("Mutated"),   tags$td(strong(paste0(n_mut, " (", pct, "%)")))),
          tags$tr(tags$td("Wild-type"), tags$td(strong(n_wt))),
          if (nrow(gf) > 0)
            tags$tr(tags$td("Most common type"),
                    tags$td(gf$Variant_Classification[1]))
        )
      )
    })

    # KM by mutation status
    output$km_mut <- renderPlot({
      req(input$gene_mut, mut_res)
      gene <- input$gene_mut
      df   <- mut_res$surv_mut
      if (!gene %in% colnames(df)) {
        return(ggplot() +
          annotate("text", x=0.5, y=0.5,
                   label=paste(gene, "not in mutation data"), size=5) + theme_void())
      }
      df_g <- df |>
        mutate(mut_status = factor(
          ifelse(.data[[gene]] == 1, paste0(gene, " mutant"), paste0(gene, " wild-type")),
          levels = c(paste0(gene, " mutant"), paste0(gene, " wild-type"))
        ))
      n_mut <- sum(df_g$mut_status == paste0(gene, " mutant"))
      if (n_mut < 5) {
        return(ggplot() +
          annotate("text", x=0.5, y=0.5,
                   label=paste0("Too few ", gene, " mutations (n=", n_mut, ") for KM."),
                   size=5) + theme_void())
      }
      km <- survfit(Surv(OS.time_m, OS) ~ mut_status, data = df_g)
      p  <- ggsurvplot(km, data = df_g,
                       palette      = c("#F44336", "#2196F3"),
                       conf.int     = TRUE, pval = TRUE, pval.method = TRUE,
                       risk.table   = TRUE,
                       xlab         = "Time (months)",
                       title        = paste0("Overall Survival by ", gene, " Mutation Status"),
                       legend.title = gene,
                       ggtheme      = theme_bw(base_size = 13))
      print(p)
    })
  })
}
